# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2bb0831ff8e5cd02191089b0fc8181c4ec2c5e8262937734bcda721dc6032fc9d047d1ff82d6dd114b8427bce71b641d31edb1bc70e19a4e3af8c4b4f8031170

test:
  secret_key_base: 7d4a8418f52aa576f87d7bd7083b1435e309d1ebd2bd00e40b58c3a420410135a9e80aa0269cd43e545489f14213db01de90d43949a589afef8e074085433b1e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
